version: '3.4'

services:
  fileservice-api:
    container_name: fileservice-api
    image: ${DOCKER_REGISTRY-}fileserviceapi
    build:
      context: .
      dockerfile: src/Services/FileService/FileService.Api/Dockerfile
    depends_on:
      - sql-server
      - consul-service
      - elasticsearch

  campaignservice-api:
    container_name: campaignservice-api
    image: ${DOCKER_REGISTRY-}campaignserviceapi
    build:
      context: .
      dockerfile: src/Services/CampaignService/CampaignService.Api/Dockerfile
    depends_on:
      - sql-server
      - consul-service
      - elasticsearch
      - redis
      - rabbitmq

  localizationservice-api:
    container_name: localizationservice-api
    image: ${DOCKER_REGISTRY-}localizationserviceapi
    build:
      context: .
      dockerfile: src/Services/LocalizationService/LocalizationService.Api/Dockerfile
    depends_on:
      - sql-server
      - consul-service
      - elasticsearch
      - redis

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest

  consul-service:
    container_name: consul-service
    image: consul

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.1

  redis:
    container_name: redis
    image: 'redis:6.0.6'

  redisinsight:
    container_name: redisinsight
    image: 'redislabs/redisinsight:latest'

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"

volumes:
  sqlserver_data:
  sqlserver_log:
  elasticsearch-data:

