version: '3.4'

services:
  fileservice-api:
    image: ${DOCKER_REGISTRY-}fileserviceapi
    build:
      context: .
      dockerfile: src/Services/FileService/FileService.Api/Dockerfile
    depends_on:
      - sql-server
      - consul-service
      - elasticsearch

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest

  consul-service:
    container_name: consul-service
    image: consul

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.1

volumes:
  sqlserver_data:
  sqlserver_log:
  elasticsearch-data: