## DEPLOYMENTS

#Redis Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379

---
## MSSQL SERVER Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/server
        name: sql-server
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: sa.++112233
        - name: MSSQL_PID
          value: Standard
        ports:
        - containerPort: 1433
          name: sql-server

---
# PostgreSQL Monitoring Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:14-alpine
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "ECSA_Monitoring"
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data-monitoring
          mountPath: /var/lib/postgresql-monitoring/data
      volumes:
      - name: postgres-data-monitoring
        emptyDir: {}

---

## SERVICES

## Redis service

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

## SQL Server service

apiVersion: v1
kind: Service
metadata:
   name: sql-server
spec:
  type: NodePort
  ports:
  - port: 1433 
    nodePort: 31433
  selector:
    app: sql-server

---

## Postgres Service

apiVersion: v1
kind: Service
metadata:
   name: postgres
spec:
  type: NodePort
  ports:
  - port: 5432 
    nodePort: 30432
  selector:
    app: postgres

